name: Deploy para Servidor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar código via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 200.135.230.253
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/ProjetoAcapraFront
            ./deploy.sh
